# Generated by Django 4.2.1 on 2023-08-01 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersname', models.CharField(max_length=30, null=True)),
                ('Account', models.CharField(max_length=30, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(max_length=30, null=True)),
                ('Accept', models.CharField(default='Waiting for accept', max_length=10, null=True)),
                ('Account_num', models.IntegerField(null=True)),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.CharField(max_length=20, null=True)),
                ('account', models.CharField(max_length=20, null=True)),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('bookss', models.CharField(max_length=10000, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('note_thingss', models.CharField(max_length=10000, null=True)),
                ('note_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reg')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urnmae', models.CharField(max_length=20, null=True)),
                ('ur_id', models.IntegerField(null=True)),
                ('uppname', models.CharField(max_length=20, null=True)),
                ('completes', models.CharField(max_length=20, null=True)),
                ('sl_id', models.CharField(max_length=20, null=True)),
                ('actrate', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('thingss', models.CharField(max_length=10000, null=True)),
                ('paid', models.CharField(max_length=20, null=True)),
                ('payss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reg')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.CharField(max_length=20, null=True)),
                ('pic', models.ImageField(max_length=20, null=True, upload_to='')),
                ('bookss', models.CharField(max_length=10000, null=True)),
                ('account', models.CharField(max_length=20, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('book_thingss', models.CharField(max_length=10, null=True)),
                ('brooks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reg')),
            ],
        ),
        migrations.CreateModel(
            name='assignmentss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs', models.CharField(max_length=20, null=True)),
                ('account', models.CharField(max_length=20, null=True)),
                ('pic', models.FileField(null=True, upload_to='')),
                ('rate', models.IntegerField(null=True)),
                ('assign_thingss', models.CharField(max_length=10, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reg')),
            ],
        ),
        migrations.CreateModel(
            name='accepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urnmae', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('Accept', models.CharField(max_length=10, null=True)),
                ('accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reg')),
            ],
        ),
    ]
